export const GET_ORGANISATIONS = 'GET_ORGANISATIONS'
export const SAVE_ORGANISATIONS = 'SAVE_ORGANISATIONS'
export const POST_ORGANISATION = 'POST_ORGANISATION'
export const IS_LOADING_ORGANISATION = 'IS_LOADING_ORGANISATION'